#!/bin/bash -e

export PATH=/var/vcap/packages/ruby/bin:$PATH
RUN_DIR=/var/vcap/sys/run/router_registrar
LOG_DIR=/var/vcap/sys/log/router_registrar
PIDFILE=$RUN_DIR/router_registrar.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "VCAP registrar"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    export CONFIG_FILE=/var/vcap/jobs/saml_login/config/router_registrar/config.yml

    cd /var/vcap/packages/saml_login/router_registrar
    exec /var/vcap/packages/ruby/bin/ruby \
         /var/vcap/packages/saml_login/router_registrar/bin/router_registrar \
         --register_with_router \
         --register_varz_credentials \
         >>$LOG_DIR/router_registrar.stdout.log \
         2>>$LOG_DIR/router_registrar.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: router_registrar_ctl {start|stop}" ;;

esac
exit 0
